spread_distance_from_spawn: 1000

allow_nether_at_day: 2

worldborder:
  start_reduce_at_day: 5 # when to start reducing the worldborder
  reduce_blocks_per_day: 10 # how many blocks to reduce per day
  radius: 1000 # from spawn this value need to be 2x bigger than spread_distance_from_spawn
  min_radius: 100 # from spawn
